name: "Publish bashclient"

on:
  workflow_dispatch:

env:
  APP_NAME: bashclient
  IMAGE_NAME: kamontat/jvsg-bashclient
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash
    working-directory: /app

permissions:
  packages: write

jobs:
  default:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: platform
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64 # linux/arm/v7

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Build Docker Metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          flavor: |
            latest: true

      - name: Build Docker image with Postgres
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.APP_NAME }}
          platforms: ${{ steps.platform.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
